# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "modern-shareholder-app"
client_id = "c322c624561b275fe13b6a13da2f3610"
application_url = "https://ears-vendor-causing-vegetation.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ears-vendor-causing-vegetation.trycloudflare.com/auth/callback",
  "https://ears-vendor-causing-vegetation.trycloudflare.com/auth/shopify/callback",
  "https://ears-vendor-causing-vegetation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mystorebs23.myshopify.com"
